name: my_project
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  uuid: ^4.5.2
  bcrypt: ^1.2.0
  dart_jsonwebtoken: ^3.3.1
  collection: ^1.19.1

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
